[platformio]
default_envs = clock

[esp32_base]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

monitor_speed = 115200

board_build.flash_size = 16MB
board_upload.flash_size = 16MB
board_build.partitions = default_16MB.csv
board_build.flash_mode = qio
board_build.arduino.memory_type = qio_opi
board_build.psram_type = opi

build_flags =
    -DBOARD_HAS_PSRAM

lib_deps =
    adafruit/Adafruit GFX Library
    adafruit/Adafruit ILI9341
    bblanchon/ArduinoJson
    olikraus/U8g2_for_Adafruit_GFX

[env:clock]
extends = esp32_base
build_src_filter =
    +<clock/>

[env:image-viewer]
extends = esp32_base
build_src_filter =
    +<image_viewer/>

[env:answer-book]
extends = esp32_base
build_src_filter =
    +<answer_book/>
lib_deps =
    ${esp32_base.lib_deps}
    paulstoffregen/XPT2046_Touchscreen

[env:clock-wokwi]
extends = env:clock
build_flags =
    ${esp32_base.build_flags}
    -DWOKWI

[env:weather-test]
extends = esp32_base
test_framework = unity
test_build_src = true
build_flags =
    ${esp32_base.build_flags}
    -Isrc/clock
build_src_filter =
    +<clock/weather_data.cpp>
test_filter = test_weather
